/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_venture_android_opencvbasic_MainActivity */

#ifndef _Included_com_venture_android_opencvbasic_MainActivity
#define _Included_com_venture_android_opencvbasic_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
#undef com_venture_android_opencvbasic_MainActivity_PERMISSION_REQUEST_CODE
#define com_venture_android_opencvbasic_MainActivity_PERMISSION_REQUEST_CODE 1L
/*
 * Class:     com_venture_android_opencvbasic_MainActivity
 * Method:    convertNativeLib
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_com_venture_android_opencvbasic_MainActivity_convertNativeLib
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     com_venture_android_opencvbasic_MainActivity
 * Method:    convertNativeGray
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_com_venture_android_opencvbasic_MainActivity_convertNativeGray
  (JNIEnv *, jobject, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
